### ISSUE TITLE
Intended behaviour - auto-install still installs when set to false

### ISSUE THREAD

**Issue by mrmartineau** [beemojs/conventional-pr-action#22]
I am not sure that this action is running correctly, can you confirm if it is supposed to install my npm dependencies given the config below:

```yml
name: Check PR title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2
        with:
          require-multiple-commits: false
          auto-install: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If `auto-install` is set to false does that mean that I need to manually install the beemo preset?
