### ISSUE TITLE
Breaking changes via ! for conventionalcommits preset not recognized

### ISSUE THREAD

**Issue by kenmaca** [beemojs/conventional-pr-action#37]
First, thanks for creating this Github Action!

I'm getting the following error: `Error: PR title doesn't follow conventional changelog format.` with the following PR title `ci(envs)!: some description here` and the following `release.yml`:

```
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
name: ci
jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-preset: conventionalcommits
```

I believe I'm setting the preset correctly to `conventionalcommits` and have also tried `auto-install: false` with the preset in my `devDependencies` but still get the same error. Any ideas?

FWIW, I tried `conventional-commits-parser` on the same commit string via CLI and got the following response:

```
% conventional-commits-parser
ci(envs)!: some description here


{"type":null,"scope":null,"subject":null,"merge":null,"header":"ci(envs)!: some description here","body":null,"footer":null,"notes":[],"references":[],"mentions":[],"revert":null}
```

The `type: null` part is suspect..
