### ISSUE TITLE
Failure while loading the angular preset

### ISSUE THREAD

**Issue by mykola-mokhnach** [beemojs/conventional-pr-action#38]
Hello
We use the following config for the action:

```
name: Conventional Commits
on:
  pull_request:


jobs:
  lint:
    name: https://www.conventionalcommits.org
    runs-on: ubuntu-latest
    steps:
    - uses: beemojs/conventional-pr-action@v2
      with:
          config-preset: angular
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Previously it was working without issue, but now the execution always fails with the following error:

```
Run beemojs/conventional-pr-action@v2
  with:
    config-preset: angular
    auto-install: true
    config-version: latest
    require-multiple-commits: false
  env:
    GITHUB_TOKEN: ***
Loading GitHub context and pull request
Installing dependencies with npm
  /usr/local/bin/npm install
  
  up to date, audited 1 package in 271ms
  
  found 0 vulnerabilities
Installing preset package conventional-changelog-angular@latest
  /usr/local/bin/npm install conventional-changelog-angular@latest
  
  added 5 packages, and audited 6 packages in 501ms
  
  found 0 vulnerabilities
Loading preset package
Error: Preset "conventional-changelog-angular" does not exist.
```

See https://github.com/appium/java-client/actions/runs/8965038536/job/24617789030?pr=2167 for more details.

Is this a genuine issue or there's something we have done wrong in the pipeline config?
